apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-post-install
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: post-install
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: post-install
        image: registry.k8s.io/kubectl:v1.32.7
        command: [
          "kubectl", "wait", "--for=condition=ready", "pod", "-n", "{{ .Release.Namespace }}",
          "-l", "app.kubernetes.io/instance={{ .Release.Name }}", "--timeout=180s" ]
      restartPolicy: Never
      serviceAccount: opentelemetry-operator
  backoffLimit: 3

